apiVersion: v1
kind: Service
metadata:
    name: helloWorld
spec:
    type: NodePort
    selector:
        app: web
    ports:
        - nodePort: 35750
          port: 8080
          targetPort: 8080